name: Prefect Grafico

on:
  schedule:
    - cron: '59 3 * * *'  # 23:59 Chile (UTC-4)
  workflow_dispatch:

jobs:
  generar-reporte:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        working-directory: prefect_notifier
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verificar matplotlib instalado
        working-directory: prefect_notifier
        run: |
          pip list
          pip show matplotlib || echo "⚠️ matplotlib no instalado"

      - name: Ejecutar grafico.py
        working-directory: prefect_notifier
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python grafico.py
